#!/usr/bin/env bash
# =============================================================================
# Samba AD DC LDAPS cert — rendered by terraform templatefile(), executed
# (sudo) on the Nomad VM that runs this DC.
#
# Replaces Samba's self-signed "temporary autogenerated" LDAPS cert with one
# issued by the lab Vault PKI (CN+SAN = dcNN.<domain>, signed by the root CA
# that Authentik/Kasm already trust) so LDAPS clients validate the DC by its
# resolvable hostname. Samba reads TLS material from the DEFAULT location
# /var/lib/samba/private/tls/{cert,key,ca}.pem (no smb.conf change needed); that
# dir is bind-mounted from the host at <dir>/samba/private/tls. The container's
# entrypoint skips provisioning on an existing domain and never regenerates
# these files, so a restart simply reloads them.
#
# templatefile vars (terraform): vault_address, vault_token, cn, tls_dir, ttl,
#   image. Shell vars use $VAR / $(...) (brace-free) so templatefile leaves them
#   literal; curl write-out %%{...} is doubled.
# =============================================================================
set -e

VAULT_ADDR="${vault_address}"
VAULT_TOKEN="${vault_token}"
CN="${cn}"
TLS_DIR="${tls_dir}"
TTL="${ttl}"
IMAGE="${image}"

echo "[+] Issuing LDAPS cert for $CN from Vault PKI (pki_int/issue/acme-certs, ttl=$TTL)..."
RESP="$(curl -sk -m15 -H "X-Vault-Token: $VAULT_TOKEN" \
  -X POST "$VAULT_ADDR/v1/pki_int/issue/acme-certs" \
  -d "$(jq -nc --arg cn "$CN" --arg ttl "$TTL" '{common_name:$cn,alt_names:$cn,ttl:$ttl}')")"
CERT="$(echo "$RESP" | jq -r '.data.certificate // empty')"
KEY="$(echo "$RESP" | jq -r '.data.private_key // empty')"
CHAIN="$(echo "$RESP" | jq -r '((.data.ca_chain // [.data.issuing_ca]) | map(select(. != null)) | join("\n")) // empty')"
if [ -z "$CERT" ] || [ -z "$KEY" ] || [ -z "$CHAIN" ]; then
  echo "[!] Vault issuance failed:"; echo "$RESP" | head -c 500; echo; exit 1
fi

echo "[+] Installing cert/key/ca into $TLS_DIR (one-time backup of the autogenerated set)..."
mkdir -p "$TLS_DIR"
for f in cert.pem key.pem ca.pem; do
  if [ -f "$TLS_DIR/$f" ] && [ ! -f "$TLS_DIR/$f.autogen.bak" ]; then
    cp -a "$TLS_DIR/$f" "$TLS_DIR/$f.autogen.bak"
  fi
done
printf '%s\n' "$CERT"  > "$TLS_DIR/cert.pem"
printf '%s\n' "$CHAIN" > "$TLS_DIR/ca.pem"
printf '%s\n' "$KEY"   > "$TLS_DIR/key.pem"
chown root:root "$TLS_DIR/cert.pem" "$TLS_DIR/ca.pem" "$TLS_DIR/key.pem"
chmod 0644 "$TLS_DIR/cert.pem" "$TLS_DIR/ca.pem"
chmod 0600 "$TLS_DIR/key.pem"

echo "[+] Restarting the Samba container to load the new cert..."
CID="$(docker ps -q --filter ancestor=$IMAGE:latest | head -1)"
[ -n "$CID" ] || CID="$(docker ps -q --filter name=samba | head -1)"
[ -n "$CID" ] || { echo "[!] Samba container not found on this host"; exit 1; }
docker restart "$CID" >/dev/null

echo "[+] Waiting for LDAPS (:636) to come back with the new (non-autogenerated) cert..."
for i in $(seq 1 40); do
  sleep 3
  ISSUER="$(echo | timeout 5 openssl s_client -connect 127.0.0.1:636 2>/dev/null | openssl x509 -noout -issuer 2>/dev/null || true)"
  [ -z "$ISSUER" ] && continue
  if ! echo "$ISSUER" | grep -q "autogenerated"; then
    echo "[+] LDAPS now serving: $ISSUER"
    exit 0
  fi
done
echo "[!] LDAPS did not come back with the Vault-issued cert in time (check 'docker logs' on this host)"
exit 1
