#!/usr/bin/env bash

# configureNomadVaultIntegration - Configure Nomad servers for Vault WIF
#
# Sets up Nomad to use Workload Identity Federation with Vault.
# No tokens stored on Nomad nodes - uses JWT-based authentication.
#
# Prerequisites:
#   - Vault deployed with WIF configured (JWT auth method)
#   - Nomad cluster running
#
# Globals read: DNS_POSTFIX, KEY_PATH, VM_USER, VAULT_CREDENTIALS_FILE
# Arguments: None
# Returns: 0 on success, 1 on failure

function configureNomadVaultIntegration() {
  cat <<EOF

############################################################################
Nomad-Vault Workload Identity Integration

Configuring Nomad servers to use Vault with Workload Identity Federation.
This is the secure, tokenless approach - no secrets stored on Nomad nodes.
#############################################################################

EOF

  ensureClusterContext || return 1

  # Get Vault address from credentials file
  if [ ! -f "$VAULT_CREDENTIALS_FILE" ]; then
    error "Vault credentials file not found: $VAULT_CREDENTIALS_FILE"
    return 1
  fi

  local VAULT_ADDR
  VAULT_ADDR=$(jq -r '.vault_address // empty' "$VAULT_CREDENTIALS_FILE")

  if [ -z "$VAULT_ADDR" ]; then
    error "Could not read vault_address from credentials file"
    return 1
  fi

  # Get all Nomad node IPs
  local ALL_NOMAD_IPS
  ALL_NOMAD_IPS=$(jq -r '.external[] | select(.hostname | startswith("nomad")) | .ip' hosts.json | cut -d'/' -f1)

  if [ -z "$ALL_NOMAD_IPS" ]; then
    error "No Nomad nodes found in hosts.json"
    return 1
  fi

  doing "Configuring Vault WIF on Nomad nodes..."

  for ip in $ALL_NOMAD_IPS; do
    local hostname
    hostname=$(jq -r --arg ip "$ip" '.external[] | select(.ip | startswith($ip)) | .hostname' hosts.json)

    doing "Configuring $hostname ($ip)..."

    # Create the Vault configuration file for WIF
    if ! sshScript "$VM_USER" "$ip" <<REMOTE_SCRIPT
      # Write Vault WIF configuration for Nomad
      sudo tee /etc/nomad.d/vault.hcl > /dev/null <<'VAULTCONFIG'
# Vault Workload Identity Federation for Nomad
# Generated by setup.sh - do not edit manually
#
# This uses JWT-based authentication - no tokens stored on disk.
# Nomad signs JWTs for each workload, Vault validates them.

vault {
  enabled = true
  address = "${VAULT_ADDR}"

  # Workload Identity configuration
  default_identity {
    aud  = ["vault.io"]
    env  = false
    file = true
    ttl  = "1h"
  }
}
VAULTCONFIG

      # Set proper permissions
      sudo chmod 644 /etc/nomad.d/vault.hcl
      sudo chown root:root /etc/nomad.d/vault.hcl

      echo "Vault WIF configuration written to /etc/nomad.d/vault.hcl"
REMOTE_SCRIPT
    then
      error "Failed to write Vault config on $hostname"
      return 1
    fi

    # Restart Nomad to apply configuration
    doing "Restarting Nomad on $hostname..."
    if ! sshRunAdmin "$VM_USER" "$ip" "sudo systemctl restart nomad"; then
      error "Failed to restart Nomad on $hostname"
      return 1
    fi

    success "Configured $hostname"
  done

  # Wait for Nomad cluster to stabilize
  doing "Waiting for Nomad cluster to stabilize..."
  sleep 10

  # Verify Nomad is healthy on first node
  local FIRST_IP
  FIRST_IP=$(echo "$ALL_NOMAD_IPS" | head -1)

  local attempts=0
  while [ $attempts -lt 30 ]; do
    if sshRunAdmin "$VM_USER" "$FIRST_IP" "nomad server members 2>/dev/null | grep -c alive" 2>/dev/null | grep -q "[3-9]"; then
      break
    fi
    sleep 2
    ((attempts++))
  done

  if [ $attempts -ge 30 ]; then
    warn "Nomad cluster may not be fully healthy. Check with: nomad server members"
  else
    success "Nomad cluster is healthy"
  fi

  echo
  info "Nomad-Vault WIF integration configured!"
  info "No tokens stored on Nomad nodes - using JWT authentication"

  success "Nomad-Vault integration complete!"
}

# Check if Nomad-Vault integration is configured
# Returns: 0 if configured, 1 if not
function isNomadVaultConfigured() {
  if [ ! -f "$VAULT_CREDENTIALS_FILE" ]; then
    return 1
  fi

  local NOMAD_IP
  NOMAD_IP=$(jq -r '.external[] | select(.hostname | startswith("nomad")) | .ip' hosts.json 2>/dev/null | head -1 | cut -d'/' -f1)

  [ -z "$NOMAD_IP" ] && return 1

  # Check if vault.hcl exists on first Nomad node
  sshRunAdmin "$VM_USER" "$NOMAD_IP" "test -f /etc/nomad.d/vault.hcl" 2>/dev/null
}
