variable "dns_postfix" {
  type = string
  description = "Domain Name Service (DNS) postfix configured"
}
variable "kasm_admin_password" {
  type = string 
  default = "changeme123"
}
variable "kasm_version" { 
  type = string
  default = "1.17.0.7f020d"
}
variable network_interface_bridge {
  type = string
  description = "Network interface for all traffic"
}

variable "lxc_storage" {
  type        = string
  description = "Storage for LXC containers (e.g., 'local-lvm', 'ceph', 'nfs-storage')"
  default     = "local-lvm"
}
variable network_gateway_address {
  type = string
  description = "Network gateway IP address"
}
variable proxmox_api_password {
  type = string 
  description = "Proxmox password for authentication"
}
variable proxmox_api_token {
  type = string
  description = "Proxmox API Token for authentication"
}
variable proxmox_api_token_id {
  type = string
  description = "Proxmox API Token ID for authentication"
}
variable proxmox_api_url {
  type = string
  description = "Proxmox API URL"
}
variable proxmox_api_username {
  type = string 
  description = "Proxmox username for authentication"
}
variable "proxmox_target_node" {
  type = string
  description = "Proxmox node"
}

variable "proxmox_node_ips" {
  type        = map(string)
  description = "Map of Proxmox node names to their IP addresses (e.g., {pve01 = \"10.1.50.210\"})"
  default     = {}
}
variable "pihole_admin_password" {
  type        = string
  description = "Pi-hole web admin password"
  sensitive   = true
}

variable "pihole_root_password" {
  type        = string
  description = "Pi-hole container root password"
  sensitive   = true
}

variable "dns_main_nodes" {
  type = list(object({
    hostname    = string
    target_node = string
    ip          = string
    gw          = string
  }))
  description = "Main DNS cluster nodes configuration (auto-generated by setup.sh)"
  default     = []
}

variable "dns_labnet_nodes" {
  type = list(object({
    hostname    = string
    target_node = string
    ip          = string
    gw          = string
  }))
  description = "Labnet SDN DNS cluster nodes configuration (auto-generated by setup.sh)"
  default     = []
}

variable "dns_primary_ipv4" {
  type        = string
  description = "Primary DNS server IP address (for other services, auto-generated by setup.sh)"
}

variable "bootstrap_dns" {
  type        = string
  description = "DNS server for main cluster provisioning (before Pi-hole is running). Use your external gateway."
  default     = "1.1.1.1"
}

variable "labnet_bootstrap_dns" {
  type        = string
  description = "DNS server for labnet SDN provisioning. Use main dns-01 IP after it's deployed, or external gateway if routable."
  default     = ""  # Empty = use bootstrap_dns value
}

variable step-ca_root_password {
  type = string
  description = "Step CA container root password"
}
variable step-ca_eth0_ipv4_cidr {
  type = string
  description = "IPv4 address with CIDR notation for Step CA"
}

# Optional second NIC for step-ca (for ACME validation across networks)
variable "step-ca_eth1_enabled" {
  type        = bool
  description = "Enable a second network interface on step-ca for ACME validation"
  default     = false
}
variable "step-ca_eth1_vmbr" {
  type        = string
  description = "Proxmox bridge for step-ca eth1"
  default     = "vmbr0"
}
variable "step-ca_eth1_ipv4_cidr" {
  type        = string
  description = "IPv4 address with CIDR for step-ca eth1"
  default     = ""
}

# SSH key for Proxmox node administration (used by Terraform provisioners)
variable "ssh_enterprise_private_key_file" {
  type        = string
  description = "Path to enterprise private key for Proxmox node SSH"
  default     = "/crypto/labenterpriseadmin"
}

# SSH key for VM/container administration (injected via cloud-init)
variable "ssh_admin_public_key_file" {
  type        = string
  description = "Path to admin public key for VM/container SSH"
  default     = "/crypto/labadmin.pub"
}

variable "vm_storage" {
  type        = string
  description = "Storage for VM disks (should match template storage for fast cloning)"
  default     = "local-lvm"
}

# Labnet DHCP Configuration
variable "labnet_dhcp_enabled" {
  type        = bool
  description = "Enable DHCP server on labnet Pi-hole"
  default     = true
}

variable "labnet_dhcp_start" {
  type        = string
  description = "Start of labnet DHCP IP range"
  default     = "172.16.0.100"
}

variable "labnet_dhcp_end" {
  type        = string
  description = "End of labnet DHCP IP range"
  default     = "172.16.0.200"
}

variable "labnet_dhcp_router" {
  type        = string
  description = "DHCP gateway/router IP for labnet (usually the SDN gateway)"
  default     = "172.16.0.1"
}

variable "labnet_dhcp_lease_time" {
  type        = string
  description = "DHCP lease time in seconds"
  default     = "86400"
}

# DNS HA Configuration (keepalived VIP)
variable "enable_dns_ha_vip" {
  type        = bool
  description = "Enable keepalived VIP for Pi-hole HA (requires privileged containers)"
  default     = false
}

variable "dns_ha_vip_address" {
  type        = string
  description = "Virtual IP address for DNS HA with CIDR (e.g., '10.1.50.3/24')"
  default     = ""
}

variable "dns_ha_vrrp_router_id" {
  type        = number
  description = "VRRP router ID for main DNS cluster (must be unique on network, 1-255)"
  default     = 51
}

variable "dns_ha_vrrp_password" {
  type        = string
  sensitive   = true
  description = "VRRP authentication password for main DNS (8 chars max)"
  default     = ""
}

# Labnet DNS HA Configuration
variable "labnet_enable_dns_ha_vip" {
  type        = bool
  description = "Enable keepalived VIP for labnet Pi-hole HA"
  default     = false
}

variable "labnet_dns_ha_vip_address" {
  type        = string
  description = "Virtual IP address for labnet DNS HA with CIDR (e.g., '172.16.0.3/24')"
  default     = ""
}

variable "labnet_dns_ha_vrrp_router_id" {
  type        = number
  description = "VRRP router ID for labnet DNS cluster (must be unique, 1-255)"
  default     = 52
}

variable "labnet_dns_ha_vrrp_password" {
  type        = string
  sensitive   = true
  description = "VRRP authentication password for labnet DNS (8 chars max)"
  default     = ""
}

# Nomad Traefik HA Configuration (keepalived VIP)
variable "nomad_traefik_ha_enabled" {
  type        = bool
  description = "Enable Traefik HA with keepalived VIP on Nomad nodes"
  default     = false
}

variable "nomad_traefik_ha_vip" {
  type        = string
  description = "Virtual IP address for Traefik HA with CIDR (e.g., '10.1.50.100/24')"
  default     = ""
}

variable "nomad_traefik_ha_vrrp_router_id" {
  type        = number
  description = "VRRP router ID for Traefik HA (must be unique on network, 1-255)"
  default     = 53
}

variable "nomad_traefik_ha_vrrp_password" {
  type        = string
  sensitive   = true
  description = "VRRP authentication password for Traefik HA (8 chars max)"
  default     = "traefik"
}