# =============================================================================
# Proxmox API Configuration (bpg/proxmox provider)
# =============================================================================

variable "proxmox_endpoint" {
  type        = string
  description = "Proxmox API endpoint URL (e.g., https://192.168.1.100:8006)"
}

variable "proxmox_api_token" {
  type        = string
  sensitive   = true
  description = "Proxmox API token in format: user@realm!token=secret"
}

variable "proxmox_ssh_username" {
  type        = string
  description = "SSH username for Proxmox node access (used by bpg provider for file uploads)"
  default     = "root"
}

variable "proxmox_target_node" {
  type        = string
  description = "Primary Proxmox node name for single-node deployments or default target"
}

variable "proxmox_node_ips" {
  type        = map(string)
  description = "Map of Proxmox node names to IP addresses (e.g., {pve01 = \"10.1.50.210\"})"
  default     = {}
}

# =============================================================================
# Network Configuration
# =============================================================================

variable "network_interface_bridge" {
  type        = string
  description = "Proxmox network bridge for VMs and containers"
}

variable "network_gateway_address" {
  type        = string
  description = "Network gateway IP address"
}

variable "bootstrap_dns" {
  type        = string
  description = "DNS server for initial provisioning (before Pi-hole is running). Typically the gateway."
}

# =============================================================================
# DNS Configuration
# =============================================================================

variable "dns_postfix" {
  type        = string
  description = "Domain suffix for all services (e.g., jdclabs.lan)"
}

variable "dns_primary_ipv4" {
  type        = string
  description = "Primary DNS server IP address (first Pi-hole node)"
}

variable "dns_main_nodes" {
  type = list(object({
    hostname    = string
    target_node = string
    ip          = string
    gw          = string
  }))
  description = "Main DNS cluster node configuration (auto-generated by bootstrap)"
  default     = []
}

# =============================================================================
# Storage Configuration
# =============================================================================

variable "template_storage" {
  type        = string
  description = "Storage for Packer templates (shared storage for clusters)"
  default     = "local-lvm"
}

variable "vm_storage" {
  type        = string
  description = "Storage for VM disks (should match template storage for fast cloning)"
  default     = "local-lvm"
}

variable "lxc_storage" {
  type        = string
  description = "Storage for LXC containers (must be block storage, not NFS/CIFS)"
  default     = "local-lvm"
}

# =============================================================================
# SSH Key Configuration
# =============================================================================

variable "ssh_enterprise_private_key_file" {
  type        = string
  description = "Path to enterprise private key for Proxmox node SSH (used by provisioners)"
  default     = "/crypto/labenterpriseadmin"
}

variable "ssh_admin_public_key_file" {
  type        = string
  description = "Path to admin public key for VM/container SSH (injected via cloud-init)"
  default     = "/crypto/labadmin.pub"
}

# =============================================================================
# Vault Configuration
# =============================================================================

variable "vault_address" {
  type        = string
  description = "Vault API address (e.g., https://10.1.50.114:8200)"
  default     = ""
}

variable "vault_token" {
  type        = string
  description = "Vault root token (from crypto/vault-credentials.json)"
  sensitive   = true
  default     = ""
}

# =============================================================================
# DNS HA Configuration (keepalived VIP)
# =============================================================================

variable "enable_dns_ha_vip" {
  type        = bool
  description = "Enable keepalived VIP for Pi-hole HA (requires privileged containers)"
  default     = false
}

variable "dns_ha_vip_address" {
  type        = string
  description = "Virtual IP for DNS HA with CIDR (e.g., '10.1.50.3/24')"
  default     = ""
}

variable "dns_ha_vrrp_router_id" {
  type        = number
  description = "VRRP router ID for DNS cluster (unique on network, 1-255)"
  default     = 51
}

variable "dns_ha_vrrp_password" {
  type        = string
  sensitive   = true
  description = "VRRP authentication password for DNS HA (8 chars max)"
  default     = ""
}

# =============================================================================
# Nomad Traefik HA Configuration (keepalived VIP)
# =============================================================================

variable "nomad_traefik_ha_enabled" {
  type        = bool
  description = "Enable Traefik HA with keepalived VIP on Nomad nodes"
  default     = false
}

variable "nomad_traefik_ha_vip" {
  type        = string
  description = "Virtual IP for Traefik HA with CIDR (e.g., '10.1.50.100/24')"
  default     = ""
}

variable "nomad_traefik_ha_vrrp_router_id" {
  type        = number
  description = "VRRP router ID for Traefik HA (unique on network, 1-255)"
  default     = 53
}

variable "nomad_traefik_ha_vrrp_password" {
  type        = string
  sensitive   = true
  description = "VRRP authentication password for Traefik HA (8 chars max)"
  default     = "traefik"
}
