# =============================================================================
# Samba AD DC — LDAPS certificate from the lab Vault PKI
#
# Out of the box each Samba DC serves LDAPS (:636) with a self-signed
# "temporary autogenerated" cert (CN-only, no SAN, not signed by the lab root
# CA). That can't be validated by LDAPS clients such as Authentik's LDAP source
# (ldaps://dcNN.<domain>). This resource issues a proper cert from Vault PKI
# (CN+SAN = dcNN.<domain>, 1y TTL, signed by the root CA those clients already
# trust), drops it into Samba's default TLS dir on the DC host, and restarts the
# container so it reloads. No smb.conf change — Samba uses private/tls/ by
# default. The entrypoint skips provisioning on an existing domain, so the
# restart is safe and non-destructive.
#
# Renewal: 1-year TTL; re-run (or taint) this resource before expiry to reissue.
# =============================================================================

locals {
  # DCs that actually exist: DC01 on nomad01 (always, when Samba AD is on),
  # DC02 on nomad02 (only when that node is in the cluster). dir = host path of
  # the DC's bind-mounted state; the TLS material lives under samba/private/tls.
  samba_dcs = var.deploy_samba_ad ? merge(
    {
      dc01 = { ip = var.nomad_node_ips["nomad01"], dir = "/opt/samba-dc01" }
    },
    contains(keys(var.nomad_node_ips), "nomad02") ? {
      dc02 = { ip = var.nomad_node_ips["nomad02"], dir = "/opt/samba-dc02" }
    } : {},
  ) : {}

  samba_image = "ghcr.io/jknyght9/samba-ad-dc"
}

resource "null_resource" "samba_ldaps_cert" {
  for_each = local.samba_dcs

  depends_on = [
    nomad_job.samba_ad,
    vault_pki_secret_backend_role.acme_certs,
  ]

  triggers = {
    cn      = "${each.key}.${var.dns_postfix}"
    tls_dir = "${each.value.dir}/samba/private/tls"
    # re-run when the install script changes
    script = filesha256("${path.module}/templates/samba-ldaps-cert.sh.tpl")
  }

  connection {
    type        = "ssh"
    host        = each.value.ip
    user        = "labadmin"
    private_key = file(var.ssh_admin_private_key_file)
  }

  provisioner "file" {
    content = templatefile("${path.module}/templates/samba-ldaps-cert.sh.tpl", {
      vault_address = var.vault_address
      vault_token   = var.vault_token
      cn            = "${each.key}.${var.dns_postfix}"
      tls_dir       = "${each.value.dir}/samba/private/tls"
      ttl           = "8760h"
      image         = local.samba_image
    })
    destination = "/tmp/samba-ldaps-cert.sh"
  }

  provisioner "remote-exec" {
    # set -e + EXIT-trap so a failed issuance/restart fails the apply instead of
    # being masked by a trailing rm (same rationale as pulse-config).
    inline = [
      "set -e",
      "trap 'rm -f /tmp/samba-ldaps-cert.sh' EXIT",
      "chmod +x /tmp/samba-ldaps-cert.sh",
      "sudo bash /tmp/samba-ldaps-cert.sh",
    ]
  }
}
